FROM eosphorosai/dbgpt:latest
ARG EXTRAS="proxy_openai,rag,storage_chromadb,quant_bnb,graph_rag"
ARG PYTHON_VERSION=3.10

ENV PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple/"
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget

RUN  /opt/.uv.venv/bin/python3 -m pip install uv -i https://mirrors.aliyun.com/pypi/simple/ && \
    extras=$(echo $EXTRAS | tr ',' '\n' | while read extra; do echo "--extra $extra"; done | tr '\n' ' ') && \
    echo $extras && \
    /opt/.uv.venv/bin/uv pip install -r pyproject.toml --all-extras && \
    # Verify installation
    python -c "import dbgpt; print(dbgpt.__version__)"