[system]
# Load language from environment variable(It is set by the hook)
language = "${env:DBGPT_LANG:-zh}"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "mysql"
path = "pilot/meta_data/dbgpt.db"
host="127.0.0.1"
port=3306
user="root"
password="qwe123Qzh!"
database="dbgpt"
[service.model.worker]
host = "127.0.0.1"

[rag.storage]
[rag.storage.vector]
type = "Chroma"
persist_path = "pilot/data"

# Model Configurations
[models]
[[models.llms]]
name = "qwen-max-latest"
provider = "proxy/tongyi"
api_key = "${env:TONGYI_API_KEY}"

[[models.embeddings]]
name = "GanymedeNil/text2vec-large-chinese"
provider = "hf"
cache_folder = "/app/models"
path = "/app/models/text2vec-large-chinese"
api_url = ""
api_key = ""

[[models.rerankers]]
type = "reranker"
name = "BAAI/bge-reranker-v2-m3"
cache_folder = "/app/models"
provider = "hf"
api_key = "${env:TONGYI_API_KEY}"
